export const TRADING_CONSTANTS = {
  DAYS_PER_YEAR: 365,
  MILLISECONDS_PER_DAY: 1000 * 60 * 60 * 24,
  DEFAULT_DECIMAL_PLACES: 2,
  INTEREST_RATE_DECIMAL_PLACES: 3,
  PERCENTAGE_MULTIPLIER: 100,
} as const;

export const FORM_VALIDATION = {
  MIN_QUANTITY: 1,
  MIN_PRICE: 0,
  PRICE_STEP: 0.0001,
} as const;

export const UI_CONSTANTS = {
  ANIMATION_DURATION: 300,
  HOVER_SCALE: 1.01,
  BUTTON_SCALE: 1.05,
} as const;



